/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package diseño;

/**
 *
 * @author feder
 */
public class GestionarOrdenes extends javax.swing.JFrame {

    /**
     * Creates new form registroDeVentas
     */
    public GestionarOrdenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        verOrdenes = new javax.swing.JButton();
        ordenDeVenta = new javax.swing.JButton();
        ordenDeDigitalizacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        borrarOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 8, 8));

        verOrdenes.setBackground(new java.awt.Color(255, 204, 204));
        verOrdenes.setText("Ver todas las ordenes");
        verOrdenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verOrdenesActionPerformed(evt);
            }
        });

        ordenDeVenta.setBackground(new java.awt.Color(255, 204, 204));
        ordenDeVenta.setText("Añadir orden de venta");
        ordenDeVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenDeVentaActionPerformed(evt);
            }
        });

        ordenDeDigitalizacion.setBackground(new java.awt.Color(255, 204, 204));
        ordenDeDigitalizacion.setText("Añadir orden de digitalizacion");
        ordenDeDigitalizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenDeDigitalizacionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTIONAR ORDENES");

        Atras.setBackground(new java.awt.Color(255, 204, 204));
        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        borrarOrden.setBackground(new java.awt.Color(255, 204, 204));
        borrarOrden.setText("Borrar orden");
        borrarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarOrdenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(ordenDeVenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(ordenDeDigitalizacion)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(borrarOrden)
                        .addGap(306, 306, 306))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Atras))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(verOrdenes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Atras)
                .addGap(70, 70, 70)
                .addComponent(verOrdenes)
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenDeVenta)
                    .addComponent(ordenDeDigitalizacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(borrarOrden)
                .addGap(62, 62, 62))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verOrdenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verOrdenesActionPerformed
        // TODO add your handling code here:
        VerOrdenes vo = new VerOrdenes();
        vo.show();
        
        dispose();
    }//GEN-LAST:event_verOrdenesActionPerformed

    private void ordenDeVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenDeVentaActionPerformed
        // TODO add your handling code here:
        OrdenDeVenta odv = new OrdenDeVenta();
        odv.show();
        
        dispose();
    }//GEN-LAST:event_ordenDeVentaActionPerformed

    private void ordenDeDigitalizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenDeDigitalizacionActionPerformed
        // TODO add your handling code here:
        OrdenDeDigitalizacion odd = new OrdenDeDigitalizacion();
        odd.show();
        
        dispose();
    }//GEN-LAST:event_ordenDeDigitalizacionActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        NewJFrame nf = new NewJFrame();
        nf.show();
        
        dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void borrarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarOrdenActionPerformed
        // TODO add your handling code here:
        BorrarOrden bo = new BorrarOrden();
        bo.show();
        
        dispose();
    }//GEN-LAST:event_borrarOrdenActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton borrarOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ordenDeDigitalizacion;
    private javax.swing.JButton ordenDeVenta;
    private javax.swing.JButton verOrdenes;
    // End of variables declaration//GEN-END:variables
}
